### ISSUE TITLE
Helm changelog with releaser

### ISSUE THREAD

**Issue by nlamirault** [chgl/kube-powertools#294]
Hi,
i try to use your tool to add a changelog to the Helm release. But release seems always default description: https://github.com/portefaix/portefaix-hub/releases/tag/ack-factory-0.3.0

Changelog generator seems ok : https://github.com/portefaix/portefaix-hub/actions/runs/4619678025/jobs/8168740019
But it is not joined to the release. Do you have any idea how to fix that ?

Thanks

**Comment by chgl** [comment]
It could be that the chart releaser isn't picking up the config. in https://github.com/chgl/charts/blob/master/.github/workflows/release.yaml#L45 I explicitly set the config file path, so maybe that's something you can try as well. Let me know how it goes!

**Comment by nlamirault** [comment]
It works ! : https://github.com/portefaix/portefaix-hub/releases/tag/crossplane-aws-factory-0.5.1
Thanks
