### ISSUE TITLE
[bug] changelog breaks when no annotations defined

### ISSUE THREAD

**Issue by christianknell** [chgl/kube-powertools#342]
If I don't define changelog-annotations in `Chart.yaml` the provided script [generate-chart-changelog.sh](https://github.com/chgl/kube-powertools/blob/master/scripts/generate-chart-changelog.sh) breaks.

`jq: error (at <stdin>:1): Cannot iterate over null (null)`

**Comment by chgl** [comment]
Ah, fair point, thanks! What's the better approach here: Create a CHANGELOG.md with just the version but no changelog entries to avoid breaking anything that depends on the file downstream, or not create a CHANGELOG.md at all?

**Comment by christianknell** [comment]
I think creating an CHANGELOG.md with just the version makes more sense.
